# admin kubeconfig
write-kubeconfig-mode: "0644"
prefer-bundled-bin: true

# logging
# debug: false

# listeners
# https-listen-port: 6443

# data
# data-dir: /var/lib/rancher/k3s

# networking
cluster-cidr: "10.42.0.0/16"
service-cidr: "10.43.0.0/16"
service-node-port-range: "30000-32767"
cluster-dns: "10.43.0.10"
cluster-domain: "cluster.local"
flannel-backend: vxlan
egress-selector-mode: disabled

# disable components coredns, servicelb, traefik, local-storage, metrics-server, runtimes
disable:
- servicelb
- traefik
# - metrics-server
# - local-storage

# storage set local-storage data dir
default-local-storage-path: /data

node-label: []
#  - role=master

# cluster options
cluster-init: true
# token: token
