#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=01

PROG=/usr/bin/k3s
K3S_CONFIG_FILE=/etc/rancher/k3s/config.yaml

start_service() {
    /sbin/modprobe br-netfilter
    /sbin/modprobe vxlan

    if [ ! -f "/etc/machine-id" ]; then
        echo -n $(head -32 /dev/urandom | md5sum | awk '{print $1}') > /etc/machine-id
    fi

    local nofile=$(cat /proc/sys/fs/nr_open)

    procd_open_instance
    procd_set_param command $PROG server --config $K3S_CONFIG_FILE
    procd_set_param limits core="unlimited"
    procd_set_param limits nofile="${nofile} ${nofile}"
    procd_set_param stdout 1 # Forward stdout of the command to logd
    procd_set_param stderr 1 # Forward stderr of the command to logd
    procd_close_instance
}

stop_service() {
    start-stop-daemon -K -q -p /var/run/k3s.pid
}

restart() {
    stop
    start
}
