#!/bin/ash

BIN_DIR=/usr/bin

for cmd in kubectl crictl ctr; do
    target="${BIN_DIR}/${cmd}"
    if [ -L "${target}" ]; then
        link_target=$(readlink "${target}")
        if [ "${link_target}" == "${BIN_DIR}/k3s" ]; then
            rm -rf ${target} && echo "removed ${target}"
        fi
    fi
done

read -p "Are you want to remove data of k3s? [N/Y]"
echo
if [[ "$REPLY" == "Y" ]] || [[ "$REPLY" == "y" ]]; then
    rm -rf /var/lib/rancher/k3s
fi
